### ISSUE TITLE
horizontal right and vertical bottom resizing lag on macOS 

### ISSUE THREAD

**Issue by Typhon0** [goxr3plus/FX-BorderlessScene#2] opened 2018-05-24 08:27 UTC
Hi, I don't know if it's the case on Windows or Linux but on macOS when I resize the windows horizontally on right and vertically on bottom ( right top and right bottom diagonal too) the resizing is lagging.

Thanks

[Demo](https://imgur.com/KA7LPcu)

**Comment by goxr3plus** [comment] 2018-05-24 14:38
Yes my dear friend it is a problem. I haven't tested it on MacOS. I am soore you can help me on fixing that issue :)

On Ubuntu it happens also.

Generally i need to fix this projdct, it has some bugs.

**Comment by Typhon0** [comment] 2018-05-24 14:51
I will try  😄

**Comment by goxr3plus** [comment] 2018-05-25 15:04
I want to see yoy doing it :)

**Comment by goxr3plus** [comment] 2018-05-30 16:11
Hey i am adding exciting new features , check the latest version :) 3.0.0

**Comment by goxr3plus** [comment] 2018-08-05 20:28
@Typhon0 Hello my dear friend , i just notices a strange bug [ NullPointerException] here : 

Line 242  [BorderlessController](https://github.com/goxr3plus/FX-BorderlessScene/blob/master/src/main/java/com/goxr3plus/fxborderlessscene/borderless/BorderlessController.java)
```JAVA
if (m.getScreenY() > eventSource.y) {
     stage.setWidth(prevSize.x);
     stage.setHeight(prevSize.y);
    snapped = false;
}
```

I am trying to investigate can you help me :) ?

#5

**Comment by goxr3plus** [comment] 2018-10-01 12:51
The issue is fixed so i am closing this . Feel free to open :)

**Closed as completed by goxr3plus** 2018-10-01 12:51 UTC
